import createType from './createType';
import getURLValueByKey from './getURLValueByKey';
import hasEmoji from './hasEmoji';
import isEmail from './isEmail';
import isIPv4 from './isIPv4';
import isIPv4Range from './isIPv4Range';
import isIPv6 from './isIPv6';
import isIPv6Range from './isIPv6Range';
import isMobile from './isMobile';
import isPhone from './isPhone';
import isPort from './isPort';
import isPostalCode from './isPostalCode';
import queryURLParams from './queryURLParams';
import validateTypeHoc from './validateTypeHoc';
export { createType, getURLValueByKey, hasEmoji, isEmail, isIPv4, isIPv4Range, isIPv6, isIPv6Range, isMobile, isPhone, isPort, isPostalCode, queryURLParams, validateTypeHoc, };
declare const _default: {
    createType: (type: string) => (value: any) => boolean;
    getURLValueByKey: (URL: string, key: string) => string;
    hasEmoji: (str: string) => boolean;
    isEmail: (str: string) => boolean;
    isIPv4: typeof isIPv4;
    isIPv4Range: typeof isIPv4Range;
    isIPv6: typeof isIPv6;
    isIPv6Range: typeof isIPv6Range;
    isMobile: (value: string | number) => boolean;
    isPhone: (value: string | number) => boolean;
    isPort: typeof isPort;
    isPostalCode: (value: string | number) => boolean;
    queryURLParams: (url: string) => any;
    validateTypeHoc: (type: string) => (value: any) => boolean;
};
export default _default;
