import addDays from './addDays';
import addHours from './addHours';
import addMinutes from './addMinutes';
import addSecs from './addSecs';
import addTime from './addTime';
import dateFormatHoc from './dateFormatHoc';
import getDatePeriod from './getDatePeriod';
import getDaysInMonth from './getDaysInMonth';
import getFirstDateInMonth from './getFirstDateInMonth';
import getLastDateInMonth from './getLastDateInMonth';
import isDate from './isDate';
import isLeapYear from './isLeapYear';
import isTime from './isTime';
import timeFormatHoc from './timeFormatHoc';
import toISOString from './toISOString';
export { addDays, addHours, addMinutes, addSecs, addTime, dateFormatHoc, getDatePeriod, getDaysInMonth, getFirstDateInMonth, getLastDateInMonth, isDate, isLeapYear, isTime, timeFormatHoc, toISOString, };
declare const _default: {
    addDays: typeof addDays;
    addHours: typeof addHours;
    addMinutes: typeof addMinutes;
    addSecs: typeof addSecs;
    addTime: typeof addTime;
    dateFormatHoc: typeof dateFormatHoc;
    getDatePeriod: typeof getDatePeriod;
    getDaysInMonth: typeof getDaysInMonth;
    getFirstDateInMonth: typeof getFirstDateInMonth;
    getLastDateInMonth: typeof getLastDateInMonth;
    isDate: typeof isDate;
    isLeapYear: typeof isLeapYear;
    isTime: typeof isTime;
    timeFormatHoc: typeof timeFormatHoc;
    toISOString: typeof toISOString;
};
export default _default;
